repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      exclude: ((?:logs|datasets|output|frames_detected|model_weights|venv|yolov[0-9]))
      language_version: python3.10.8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    - id: mypy
      args: ["--exclude=\"((?:logs|datasets|output|PixelFormer|frames_detected|model_weights|venv|yolov[0-9]))\"", "--ignore-missing-imports"]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args:
          [
              "--exit-zero",
              "--output-format=text",
              "--ignore-patterns=\"((?:logs|datasets|output|frames_detected|model_weights|venv|yolov[0-9]))\""
          ]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ["--ignore-self-only-init", "--ignore=D100,D104,D213,D203,D404", "--match-dir=\"^(?:(?!logs|datasets|output|PixelFormer|frames_detected|model_weights|notebooks|venv|yolov[0-9]).)*$\""]