from .shake_detection.shake_detection import ShakeDetection
from .depth_map.depth_map_utils import DepthModel
from .object_detection.yolov4.object_detection import ObjectDetection as ObjectDetectionYoloV4
from .object_detection.yolov5.object_detection import ObjectDetection as ObjectDetectionCustom
